name: smart_farming_demo_mobile
description: A Flutter demo app for smart farming awareness.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+5
  tflite_flutter: ^0.11.0
  tflite_flutter_helper: ^0.3.0
  image: ^4.0.17
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/model.tflite
    - assets/models/labels.txt
